### ISSUE TITLE
为何我添加的卡片显示出来的窗口非常小呢？

### ISSUE THREAD

**Issue by alonemars** [FrostZhang/hass_unity_home#5]
![图片](https://user-images.githubusercontent.com/45503809/174741761-135d3576-40d4-4a99-a403-ba90f04401db.png)
如图，这是因为什么会导致这么小的呢？

**Comment by alonemars** [comment]
并且点完上面第二个画笔后编辑的东西也没有办法保存，这是什么情况呢？

**Comment by FrostZhang** [comment]
请仔细阅读 Readme 和 说明书
